services:
  phonetics-app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=false
      - PORT=8000
    volumes:
      # Optionally mount data directory for easier updates
      # - ./data:/app/data:ro
      # Mount logs directory
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/', timeout=10)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
